export const FETCH_TRANSACTIONS_INITIATED = 'FETCH_TRANSACTIONS_INITIATED'
export const FETCH_TRANSACTIONS_SUCCESS = 'FETCH_TRANSACTIONS_SUCCESS'
export const FETCH_TRANSACTIONS_FAILED = 'FETCH_TRANSACTIONS_FAILED'

export const RESET_TRANSACTIONS_LIST_STATE = 'RESET_TRANSACTIONS_LIST_STATE'
export const SELECT_CHANGE_TRANSACTIONS_LIST = 'SELECT_CHANGE_TRANSACTIONS_LIST'
export const PAGE_CHANGE_LIST_TRANSACTIONS = 'SELECT_CHANGE_TRANSACTIONS_LIST'
